import type { JourneyTask } from "./ventureJourney.ts";

/** Stable keys are persisted: never rename/reuse one when changing the copy. */
export const JOURNEY_TEMPLATES: JourneyTask[] = [
  {
    "key": "idea:common:customer",
    "stage": "idea",
    "businessType": null,
    "title": "Describe your first customer",
    "detail": "Choose a specific person or business and the situation that creates the need.",
    "evidenceHint": "A short customer profile with a real use case.",
    "tool": "Research agent",
    "group": "Understand the opportunity",
    "required": true
  },
  {
    "key": "idea:common:problem",
    "stage": "idea",
    "businessType": null,
    "title": "Write the problem in one sentence",
    "detail": "Describe the problem without naming your solution. Record what people do today.",
    "evidenceHint": "One clear problem and the current workaround.",
    "tool": "Product knowledge",
    "group": "Understand the opportunity",
    "required": true
  },
  {
    "key": "idea:common:alternatives",
    "stage": "idea",
    "businessType": null,
    "title": "Map the alternatives",
    "detail": "Compare direct competitors, manual workarounds and doing nothing.",
    "evidenceHint": "Three alternatives, their strengths, gaps and pricing evidence.",
    "tool": "Competitor analyst",
    "group": "Understand the opportunity",
    "required": false
  },
  {
    "key": "idea:common:names",
    "stage": "idea",
    "businessType": null,
    "title": "Build a name & domain shortlist",
    "detail": "Shortlist memorable names. Check real domain availability, existing brands and social handles before choosing.",
    "evidenceHint": "Three candidate names with links to your own checks.",
    "tool": "Names workspace",
    "group": "Shape the concept",
    "required": false
  },
  {
    "key": "idea:common:offer",
    "stage": "idea",
    "businessType": null,
    "title": "Choose a first offer and revenue model",
    "detail": "Make the smallest useful promise and identify who would pay, for what, and when.",
    "evidenceHint": "A first offer with assumptions about price and delivery.",
    "tool": "Product knowledge",
    "group": "Shape the concept",
    "required": true
  },
  {
    "key": "idea:common:decision",
    "stage": "idea",
    "businessType": null,
    "title": "Decide: proceed, adapt or pause",
    "detail": "Review the evidence and choose the next experiment or a clear reason to pause.",
    "evidenceHint": "A dated decision and the assumption to test next.",
    "tool": "Chief of Staff",
    "group": "Make a decision",
    "required": true
  },
  {
    "key": "pre-launch:common:scope",
    "stage": "pre-launch",
    "businessType": null,
    "title": "Lock the first version and its promise",
    "detail": "Separate launch essentials from improvements that can follow.",
    "evidenceHint": "A short scope with a clear end-to-end customer outcome.",
    "tool": "Board",
    "group": "Customer experience",
    "required": true
  },
  {
    "key": "pre-launch:common:identity",
    "stage": "pre-launch",
    "businessType": null,
    "title": "Set the name, domain and brand basics",
    "detail": "Choose the identity and document ownership of the domain and key accounts.",
    "evidenceHint": "A final name, identity assets and account ownership notes.",
    "tool": "Dynadot / Spaceship",
    "group": "Customer experience",
    "required": false
  },
  {
    "key": "pre-launch:common:support",
    "stage": "pre-launch",
    "businessType": null,
    "title": "Set up a support route and useful replies",
    "detail": "Decide how customers can reach you and prepare answers to likely questions.",
    "evidenceHint": "A tested support address or contact route.",
    "tool": "Gmail / Resend",
    "group": "Be ready for customers",
    "required": true
  },
  {
    "key": "pre-launch:common:disclosures",
    "stage": "pre-launch",
    "businessType": null,
    "title": "Review customer information and obligations",
    "detail": "Review the disclosures, consent, accessibility and operating requirements relevant to your product and location.",
    "evidenceHint": "Your review notes and the customer-facing information.",
    "tool": "Manual review",
    "group": "Be ready for customers",
    "required": true
  },
  {
    "key": "pre-launch:common:launch-plan",
    "stage": "pre-launch",
    "businessType": null,
    "title": "Choose a launch audience and first-week plan",
    "detail": "Decide who should hear about this first, which channel you will use, and how you will measure the response.",
    "evidenceHint": "A launch date, audience, message and first-week review.",
    "tool": "Calendar / Studio",
    "group": "Launch deliberately",
    "required": false
  },
  {
    "key": "launched:common:weekly",
    "stage": "launched",
    "businessType": null,
    "title": "Review the week’s numbers",
    "detail": "Compare like-for-like periods and identify what changed. Keep unknown data distinct from zero.",
    "evidenceHint": "A short weekly review with one decision.",
    "tool": "Insights",
    "group": "Weekly rhythm",
    "required": false
  },
  {
    "key": "launched:common:customers",
    "stage": "launched",
    "businessType": null,
    "title": "Read customer conversations",
    "detail": "Look for repeat questions, friction and signs that the product is working.",
    "evidenceHint": "Three themes from support, interviews or reviews.",
    "tool": "Gmail / People analyst",
    "group": "Weekly rhythm",
    "required": false
  },
  {
    "key": "launched:common:next-test",
    "stage": "launched",
    "businessType": null,
    "title": "Choose one improvement to test",
    "detail": "Start with the problem, assign an owner, and choose the measurement before shipping.",
    "evidenceHint": "One scoped experiment and a review date.",
    "tool": "Board",
    "group": "Improve deliberately",
    "required": false
  },
  {
    "key": "launched:common:costs",
    "stage": "launched",
    "businessType": null,
    "title": "Check margin, costs and upcoming renewals",
    "detail": "Review expenses against the venture’s income and spot commitments that need a decision.",
    "evidenceHint": "A monthly cost review with necessary follow-ups.",
    "tool": "Finance / Domains",
    "group": "Monthly housekeeping",
    "required": false
  },
  {
    "key": "idea:web:test-the-main-workflow-with-five-people",
    "stage": "idea",
    "businessType": "web",
    "title": "Test the main workflow with five people",
    "detail": "Use a sketch or clickable prototype before committing to a build.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Research agent",
    "group": "Test the business",
    "required": false
  },
  {
    "key": "idea:web:decide-what-belongs-in-the-first-web-app",
    "stage": "idea",
    "businessType": "web",
    "title": "Decide what belongs in the first web app",
    "detail": "Map one successful journey from sign-up to a useful result.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Product knowledge",
    "group": "Test the business",
    "required": false
  },
  {
    "key": "idea:web:test-interest-in-the-paid-offer",
    "stage": "idea",
    "businessType": "web",
    "title": "Test interest in the paid offer",
    "detail": "Ask for a specific next action, such as a pilot or a waitlist sign-up.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Demand analyst",
    "group": "Test the business",
    "required": false
  },
  {
    "key": "pre-launch:web:test-sign-up-the-core-workflow-and-account-deletion",
    "stage": "pre-launch",
    "businessType": "web",
    "title": "Test sign-up, the core workflow and account deletion",
    "detail": "Walk through the full customer journey on supported browsers.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "GitHub",
    "group": "Launch essentials",
    "required": true
  },
  {
    "key": "pre-launch:web:test-billing-cancellation-and-receipts",
    "stage": "pre-launch",
    "businessType": "web",
    "title": "Test billing, cancellation and receipts",
    "detail": "Exercise the intended billing paths in an appropriate test environment.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Stripe",
    "group": "Launch essentials",
    "required": true
  },
  {
    "key": "pre-launch:web:test-backups-restoration-and-rollback",
    "stage": "pre-launch",
    "businessType": "web",
    "title": "Test backups, restoration and rollback",
    "detail": "Record a recovery procedure and test that it works.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Fleet / GitHub",
    "group": "Launch essentials",
    "required": true
  },
  {
    "key": "pre-launch:web:connect-analytics-and-health-monitoring",
    "stage": "pre-launch",
    "businessType": "web",
    "title": "Connect analytics and health monitoring",
    "detail": "Define the key activation event and monitor the app’s critical endpoints.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Umami / Uptime",
    "group": "Launch essentials",
    "required": false
  },
  {
    "key": "pre-launch:web:invite-a-small-pilot-group",
    "stage": "pre-launch",
    "businessType": "web",
    "title": "Invite a small pilot group",
    "detail": "Collect feedback and close the most important issues before wider release.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Resend",
    "group": "Launch essentials",
    "required": false
  },
  {
    "key": "launched:web:review-activation-and-recurring-revenue",
    "stage": "launched",
    "businessType": "web",
    "title": "Review activation and recurring revenue",
    "detail": "Find friction between sign-up and the first useful outcome.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Umami / Stripe",
    "group": "Operating rhythm",
    "required": false
  },
  {
    "key": "launched:web:check-incidents-backups-and-releases",
    "stage": "launched",
    "businessType": "web",
    "title": "Check incidents, backups and releases",
    "detail": "Review open problems and confirm recent changes are behaving as intended.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "GitHub / Fleet",
    "group": "Operating rhythm",
    "required": false
  },
  {
    "key": "launched:web:follow-up-with-customers-at-risk-of-leaving",
    "stage": "launched",
    "businessType": "web",
    "title": "Follow up with customers at risk of leaving",
    "detail": "Use direct customer evidence before deciding what should change.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "App users / Gmail",
    "group": "Operating rhythm",
    "required": false
  },
  {
    "key": "idea:mobile:choose-ios-android-or-both",
    "stage": "idea",
    "businessType": "mobile",
    "title": "Choose iOS, Android or both",
    "detail": "Consider the audience, device needs and smallest useful first release.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Product knowledge",
    "group": "Test the business",
    "required": false
  },
  {
    "key": "idea:mobile:test-the-core-habit-on-a-phone",
    "stage": "idea",
    "businessType": "mobile",
    "title": "Test the core habit on a phone",
    "detail": "Run a short prototype test on the devices people actually use.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Research agent",
    "group": "Test the business",
    "required": false
  },
  {
    "key": "idea:mobile:read-competing-app-reviews",
    "stage": "idea",
    "businessType": "mobile",
    "title": "Read competing app reviews",
    "detail": "Record the unmet needs behind repeat complaints, with links to the reviews.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "ASO analyst",
    "group": "Test the business",
    "required": false
  },
  {
    "key": "pre-launch:mobile:test-on-real-devices-and-slow-connections",
    "stage": "pre-launch",
    "businessType": "mobile",
    "title": "Test on real devices and slow connections",
    "detail": "Cover the key devices, permissions, offline behavior and first-run experience.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "GitHub",
    "group": "Launch essentials",
    "required": true
  },
  {
    "key": "pre-launch:mobile:prepare-store-listings-and-a-review-build",
    "stage": "pre-launch",
    "businessType": "mobile",
    "title": "Prepare store listings and a review build",
    "detail": "Gather screenshots, accurate descriptions, review access and current platform requirements.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "App Store / Google Play",
    "group": "Launch essentials",
    "required": true
  },
  {
    "key": "pre-launch:mobile:verify-purchases-and-restoration",
    "stage": "pre-launch",
    "businessType": "mobile",
    "title": "Verify purchases and restoration",
    "detail": "Check the intended payment, cancellation and purchase-restoration experience.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "App Store / Google Play",
    "group": "Launch essentials",
    "required": true
  },
  {
    "key": "pre-launch:mobile:connect-crash-and-release-monitoring",
    "stage": "pre-launch",
    "businessType": "mobile",
    "title": "Connect crash and release monitoring",
    "detail": "Make sure a problem can be tied to the affected app and release.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Mobile health",
    "group": "Launch essentials",
    "required": true
  },
  {
    "key": "pre-launch:mobile:run-a-focused-beta-and-triage-feedback",
    "stage": "pre-launch",
    "businessType": "mobile",
    "title": "Run a focused beta and triage feedback",
    "detail": "Give testers a clear task and resolve the issues that block its completion.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Gmail / Board",
    "group": "Launch essentials",
    "required": false
  },
  {
    "key": "launched:mobile:review-crashes-by-app-and-version",
    "stage": "launched",
    "businessType": "mobile",
    "title": "Review crashes by app and version",
    "detail": "Prioritize repeated failures in the core experience.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Mobile health",
    "group": "Operating rhythm",
    "required": false
  },
  {
    "key": "launched:mobile:read-store-reviews-and-funnel-changes",
    "stage": "launched",
    "businessType": "mobile",
    "title": "Read store reviews and funnel changes",
    "detail": "Look at feedback alongside visits, installs and retention.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "ASO analyst",
    "group": "Operating rhythm",
    "required": false
  },
  {
    "key": "launched:mobile:check-receipts-subscription-changes-and-releases",
    "stage": "launched",
    "businessType": "mobile",
    "title": "Check receipts, subscription changes and releases",
    "detail": "Review each platform separately before combining unlike measurements.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "App Store / Google Play",
    "group": "Operating rhythm",
    "required": false
  },
  {
    "key": "idea:desktop:choose-supported-operating-systems",
    "stage": "idea",
    "businessType": "desktop",
    "title": "Choose supported operating systems",
    "detail": "Match the first platform to the people and workflows you understand best.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Product knowledge",
    "group": "Test the business",
    "required": false
  },
  {
    "key": "idea:desktop:validate-why-this-should-live-on-a-desktop",
    "stage": "idea",
    "businessType": "desktop",
    "title": "Validate why this should live on a desktop",
    "detail": "Test whether local files, offline use or system integration creates real value.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Research agent",
    "group": "Test the business",
    "required": false
  },
  {
    "key": "idea:desktop:test-a-license-or-subscription-offer",
    "stage": "idea",
    "businessType": "desktop",
    "title": "Test a license or subscription offer",
    "detail": "Ask potential customers to choose between concrete delivery and pricing options.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Demand analyst",
    "group": "Test the business",
    "required": false
  },
  {
    "key": "pre-launch:desktop:test-installation-launch-and-uninstall",
    "stage": "pre-launch",
    "businessType": "desktop",
    "title": "Test installation, launch and uninstall",
    "detail": "Cover a clean install, an existing install and ordinary permission levels.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "GitHub",
    "group": "Launch essentials",
    "required": true
  },
  {
    "key": "pre-launch:desktop:prepare-signing-and-distribution-checks",
    "stage": "pre-launch",
    "businessType": "desktop",
    "title": "Prepare signing and distribution checks",
    "detail": "Review the requirements for each intended operating system and distribution channel.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Manual review",
    "group": "Launch essentials",
    "required": true
  },
  {
    "key": "pre-launch:desktop:test-updates-and-rollback",
    "stage": "pre-launch",
    "businessType": "desktop",
    "title": "Test updates and rollback",
    "detail": "Verify the update path, failed-download recovery and a safe fallback.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "GitHub",
    "group": "Launch essentials",
    "required": true
  },
  {
    "key": "pre-launch:desktop:test-licensing-offline-use-and-data-recovery",
    "stage": "pre-launch",
    "businessType": "desktop",
    "title": "Test licensing, offline use and data recovery",
    "detail": "Cover the intended license states, missing connectivity and recovery of user work.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Stripe / Product endpoints",
    "group": "Launch essentials",
    "required": true
  },
  {
    "key": "pre-launch:desktop:prepare-downloads-and-a-beta-cohort",
    "stage": "pre-launch",
    "businessType": "desktop",
    "title": "Prepare downloads and a beta cohort",
    "detail": "Provide checksummed builds, release notes and a clear feedback route.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "GitHub / Gmail",
    "group": "Launch essentials",
    "required": false
  },
  {
    "key": "launched:desktop:check-crashes-and-operating-system-compatibility",
    "stage": "launched",
    "businessType": "desktop",
    "title": "Check crashes and operating-system compatibility",
    "detail": "Group failures by version and platform.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Product endpoints",
    "group": "Operating rhythm",
    "required": false
  },
  {
    "key": "launched:desktop:review-update-adoption-and-delivery",
    "stage": "launched",
    "businessType": "desktop",
    "title": "Review update adoption and delivery",
    "detail": "Find customers who are stranded on old builds.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "GitHub / App users",
    "group": "Operating rhythm",
    "required": false
  },
  {
    "key": "launched:desktop:review-licenses-refunds-and-support-themes",
    "stage": "launched",
    "businessType": "desktop",
    "title": "Review licenses, refunds and support themes",
    "detail": "Use license activity and conversations to choose the next improvement.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Stripe / Gmail",
    "group": "Operating rhythm",
    "required": false
  },
  {
    "key": "idea:website:choose-a-focused-topic-and-reader-need",
    "stage": "idea",
    "businessType": "website",
    "title": "Choose a focused topic and reader need",
    "detail": "Start with a useful niche that you can serve consistently.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Research agent",
    "group": "Test the business",
    "required": false
  },
  {
    "key": "idea:website:test-demand-for-a-few-specific-pages",
    "stage": "idea",
    "businessType": "website",
    "title": "Test demand for a few specific pages",
    "detail": "Use search and audience evidence to prioritize real questions.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "SEO / Demand analyst",
    "group": "Test the business",
    "required": false
  },
  {
    "key": "idea:website:choose-how-the-site-creates-value",
    "stage": "idea",
    "businessType": "website",
    "title": "Choose how the site creates value",
    "detail": "Decide whether success means leads, readership, memberships, sales or another outcome.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Product knowledge",
    "group": "Test the business",
    "required": false
  },
  {
    "key": "pre-launch:website:check-the-main-pages-and-navigation",
    "stage": "pre-launch",
    "businessType": "website",
    "title": "Check the main pages and navigation",
    "detail": "Verify key links, readable layouts and the intended mobile experience.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Site audit",
    "group": "Launch essentials",
    "required": true
  },
  {
    "key": "pre-launch:website:test-forms-and-subscription-emails",
    "stage": "pre-launch",
    "businessType": "website",
    "title": "Test forms and subscription emails",
    "detail": "Make sure a reader can complete the intended action and receive a useful response.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Resend / Gmail",
    "group": "Launch essentials",
    "required": true
  },
  {
    "key": "pre-launch:website:review-crawlability-and-page-metadata",
    "stage": "pre-launch",
    "businessType": "website",
    "title": "Review crawlability and page metadata",
    "detail": "Check the sitemap, index settings and useful titles for important pages.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "SEO / Search Console",
    "group": "Launch essentials",
    "required": true
  },
  {
    "key": "pre-launch:website:connect-analytics-and-uptime-checks",
    "stage": "pre-launch",
    "businessType": "website",
    "title": "Connect analytics and uptime checks",
    "detail": "Choose a meaningful conversion and monitor the pages that matter.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Umami / Uptime",
    "group": "Launch essentials",
    "required": false
  },
  {
    "key": "pre-launch:website:prepare-the-first-publishing-rhythm",
    "stage": "pre-launch",
    "businessType": "website",
    "title": "Prepare the first publishing rhythm",
    "detail": "Have useful launch content and a manageable plan for what comes next.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Studio / Writer",
    "group": "Launch essentials",
    "required": false
  },
  {
    "key": "launched:website:review-search-traffic-and-important-pages",
    "stage": "launched",
    "businessType": "website",
    "title": "Review search traffic and important pages",
    "detail": "Distinguish a content issue from an indexing or availability problem.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Search Console / SEO",
    "group": "Operating rhythm",
    "required": false
  },
  {
    "key": "launched:website:update-content-and-broken-links",
    "stage": "launched",
    "businessType": "website",
    "title": "Update content and broken links",
    "detail": "Refresh information that readers rely on and fix their dead ends.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Site audit / Writer",
    "group": "Operating rhythm",
    "required": false
  },
  {
    "key": "launched:website:review-leads-subscriptions-or-earnings",
    "stage": "launched",
    "businessType": "website",
    "title": "Review leads, subscriptions or earnings",
    "detail": "Use the outcome you chose rather than pageviews alone.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Umami / AdSense",
    "group": "Operating rhythm",
    "required": false
  },
  {
    "key": "idea:shop:choose-the-location-and-customer-catchment",
    "stage": "idea",
    "businessType": "shop",
    "title": "Choose the location and customer catchment",
    "detail": "Observe who visits the area, when they shop and what is already available.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Research agent",
    "group": "Test the business",
    "required": false
  },
  {
    "key": "idea:shop:test-a-small-assortment-at-a-pop-up",
    "stage": "idea",
    "businessType": "shop",
    "title": "Test a small assortment at a pop-up",
    "detail": "Learn which products people actually buy before committing to a larger range.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Manual evidence",
    "group": "Test the business",
    "required": false
  },
  {
    "key": "idea:shop:estimate-setup-stock-and-operating-needs",
    "stage": "idea",
    "businessType": "shop",
    "title": "Estimate setup, stock and operating needs",
    "detail": "List startup commitments and test the assumptions behind a typical trading week.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Finance workspace",
    "group": "Test the business",
    "required": false
  },
  {
    "key": "pre-launch:shop:confirm-the-premises-and-opening-requirements",
    "stage": "pre-launch",
    "businessType": "shop",
    "title": "Confirm the premises and opening requirements",
    "detail": "Review site readiness and the requirements that apply to this type of shop and location.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Manual review",
    "group": "Launch essentials",
    "required": true
  },
  {
    "key": "pre-launch:shop:test-the-register-payments-and-returns",
    "stage": "pre-launch",
    "businessType": "shop",
    "title": "Test the register, payments and returns",
    "detail": "Walk through a purchase, failed payment, receipt and return.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "POS data · custom",
    "group": "Launch essentials",
    "required": true
  },
  {
    "key": "pre-launch:shop:receive-and-count-opening-inventory",
    "stage": "pre-launch",
    "businessType": "shop",
    "title": "Receive and count opening inventory",
    "detail": "Check quantities, shelf labels, supplier details and reorder points.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Inventory · custom",
    "group": "Launch essentials",
    "required": true
  },
  {
    "key": "pre-launch:shop:plan-opening-hours-and-daily-routines",
    "stage": "pre-launch",
    "businessType": "shop",
    "title": "Plan opening hours and daily routines",
    "detail": "Prepare opening, closing, security and customer-support routines.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Google Calendar",
    "group": "Launch essentials",
    "required": true
  },
  {
    "key": "pre-launch:shop:publish-location-details-and-an-opening-plan",
    "stage": "pre-launch",
    "businessType": "shop",
    "title": "Publish location details and an opening plan",
    "detail": "Make it easy for local customers to find the shop and know when to visit.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Studio / Website",
    "group": "Launch essentials",
    "required": false
  },
  {
    "key": "launched:shop:reconcile-sales-and-payment-settlements",
    "stage": "launched",
    "businessType": "shop",
    "title": "Reconcile sales and payment settlements",
    "detail": "Compare the register and received funds for the same trading period.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "POS data · custom",
    "group": "Operating rhythm",
    "required": false
  },
  {
    "key": "launched:shop:review-low-stock-shrinkage-and-supplier-orders",
    "stage": "launched",
    "businessType": "shop",
    "title": "Review low stock, shrinkage and supplier orders",
    "detail": "Use reorder points and actual demand to prepare the next order.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Inventory · custom",
    "group": "Operating rhythm",
    "required": false
  },
  {
    "key": "launched:shop:review-footfall-baskets-and-repeat-customers",
    "stage": "launched",
    "businessType": "shop",
    "title": "Review footfall, baskets and repeat customers",
    "detail": "Choose one change to the assortment or in-store experience.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Custom data / Journal",
    "group": "Operating rhythm",
    "required": false
  },
  {
    "key": "idea:goods:define-the-first-product-and-target-buyer",
    "stage": "idea",
    "businessType": "goods",
    "title": "Define the first product and target buyer",
    "detail": "Choose a concrete use case, the smallest range and what makes it useful.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Research agent",
    "group": "Test the business",
    "required": false
  },
  {
    "key": "idea:goods:test-a-sample-with-potential-buyers",
    "stage": "idea",
    "businessType": "goods",
    "title": "Test a sample with potential buyers",
    "detail": "Collect specific feedback on function, finish, packaging and the intended price.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Manual evidence",
    "group": "Test the business",
    "required": false
  },
  {
    "key": "idea:goods:map-sourcing-and-per-order-economics",
    "stage": "idea",
    "businessType": "goods",
    "title": "Map sourcing and per-order economics",
    "detail": "List making, packing, shipping, support and return assumptions before ordering.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Finance workspace",
    "group": "Test the business",
    "required": false
  },
  {
    "key": "pre-launch:goods:approve-a-sample-and-supplier-quality-checks",
    "stage": "pre-launch",
    "businessType": "goods",
    "title": "Approve a sample and supplier quality checks",
    "detail": "Record the agreed specification and how each batch will be checked.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Manual review",
    "group": "Launch essentials",
    "required": true
  },
  {
    "key": "pre-launch:goods:confirm-product-and-packaging-requirements",
    "stage": "pre-launch",
    "businessType": "goods",
    "title": "Confirm product and packaging requirements",
    "detail": "Review requirements for the product, its claims and intended selling locations.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Manual review",
    "group": "Launch essentials",
    "required": true
  },
  {
    "key": "pre-launch:goods:test-checkout-fulfilment-and-returns",
    "stage": "pre-launch",
    "businessType": "goods",
    "title": "Test checkout, fulfilment and returns",
    "detail": "Place a test order and follow it through the entire customer journey.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Orders · custom",
    "group": "Launch essentials",
    "required": true
  },
  {
    "key": "pre-launch:goods:set-stock-levels-and-dispatch-expectations",
    "stage": "pre-launch",
    "businessType": "goods",
    "title": "Set stock levels and dispatch expectations",
    "detail": "Record stock on hand, lead times and what the customer will be promised.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Inventory · custom",
    "group": "Launch essentials",
    "required": true
  },
  {
    "key": "pre-launch:goods:prepare-product-photos-and-accurate-descriptions",
    "stage": "pre-launch",
    "businessType": "goods",
    "title": "Prepare product photos and accurate descriptions",
    "detail": "Show what buyers will receive, including relevant dimensions and care details.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Studio / Writer",
    "group": "Launch essentials",
    "required": false
  },
  {
    "key": "launched:goods:clear-fulfilment-exceptions-and-returns",
    "stage": "launched",
    "businessType": "goods",
    "title": "Clear fulfilment exceptions and returns",
    "detail": "Start with paid orders that have missed their promised next step.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Orders · custom",
    "group": "Operating rhythm",
    "required": false
  },
  {
    "key": "launched:goods:check-stock-coverage-and-supplier-performance",
    "stage": "launched",
    "businessType": "goods",
    "title": "Check stock coverage and supplier performance",
    "detail": "Compare current demand with lead times before reordering.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Inventory · custom",
    "group": "Operating rhythm",
    "required": false
  },
  {
    "key": "launched:goods:review-margin-after-fulfilment-and-returns",
    "stage": "launched",
    "businessType": "goods",
    "title": "Review margin after fulfilment and returns",
    "detail": "Include cost of goods and the costs of delivering each order.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Finance workspace",
    "group": "Operating rhythm",
    "required": false
  },
  {
    "key": "idea:service:define-a-small-clear-service-package",
    "stage": "idea",
    "businessType": "service",
    "title": "Define a small, clear service package",
    "detail": "Name the outcome, delivery format and what is outside the scope.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Product knowledge",
    "group": "Test the business",
    "required": false
  },
  {
    "key": "idea:service:talk-to-potential-clients-and-test-the-offer",
    "stage": "idea",
    "businessType": "service",
    "title": "Talk to potential clients and test the offer",
    "detail": "Ask for a real commitment to a scoped pilot, not only feedback.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Research agent / Gmail",
    "group": "Test the business",
    "required": false
  },
  {
    "key": "idea:service:map-capacity-and-delivery-costs",
    "stage": "idea",
    "businessType": "service",
    "title": "Map capacity and delivery costs",
    "detail": "Estimate the work involved and the number of clients you can serve well.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Calendar / Finance",
    "group": "Test the business",
    "required": false
  },
  {
    "key": "pre-launch:service:prepare-a-proposal-scope-and-working-agreement",
    "stage": "pre-launch",
    "businessType": "service",
    "title": "Prepare a proposal, scope and working agreement",
    "detail": "Make the deliverables, timing and customer responsibilities clear.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Writer / Manual review",
    "group": "Launch essentials",
    "required": true
  },
  {
    "key": "pre-launch:service:test-enquiry-booking-and-payment",
    "stage": "pre-launch",
    "businessType": "service",
    "title": "Test enquiry, booking and payment",
    "detail": "Follow the entire path from first contact to a confirmed engagement.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Calendar / Stripe",
    "group": "Launch essentials",
    "required": true
  },
  {
    "key": "pre-launch:service:prepare-onboarding-and-delivery-templates",
    "stage": "pre-launch",
    "businessType": "service",
    "title": "Prepare onboarding and delivery templates",
    "detail": "Make the first handoff easy for the customer and repeatable for you.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Product knowledge",
    "group": "Launch essentials",
    "required": true
  },
  {
    "key": "pre-launch:service:set-support-and-communication-expectations",
    "stage": "pre-launch",
    "businessType": "service",
    "title": "Set support and communication expectations",
    "detail": "Agree where updates happen and how questions are handled.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Gmail",
    "group": "Launch essentials",
    "required": true
  },
  {
    "key": "pre-launch:service:prepare-evidence-and-the-first-outreach-list",
    "stage": "pre-launch",
    "businessType": "service",
    "title": "Prepare evidence and the first outreach list",
    "detail": "Use relevant examples and a small audience you can serve well.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Studio / Gmail",
    "group": "Launch essentials",
    "required": false
  },
  {
    "key": "launched:service:review-bookings-capacity-and-delivery-promises",
    "stage": "launched",
    "businessType": "service",
    "title": "Review bookings, capacity and delivery promises",
    "detail": "Surface deadlines or workloads that need a decision early.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Google Calendar / Board",
    "group": "Operating rhythm",
    "required": false
  },
  {
    "key": "launched:service:follow-up-on-proposals-and-invoices",
    "stage": "launched",
    "businessType": "service",
    "title": "Follow up on proposals and invoices",
    "detail": "Keep each follow-up specific to the client and the agreed next step.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Gmail / Stripe",
    "group": "Operating rhythm",
    "required": false
  },
  {
    "key": "launched:service:capture-outcomes-referrals-and-repeat-needs",
    "stage": "launched",
    "businessType": "service",
    "title": "Capture outcomes, referrals and repeat needs",
    "detail": "Turn completed work into a better service and useful proof.",
    "evidenceHint": "Record what you learned, the result, and a link or next decision.",
    "tool": "Journal / Product knowledge",
    "group": "Operating rhythm",
    "required": false
  }
];
