import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { upsertPlugin, setConfig, configValue } from "../../../db.ts";
import * as accounts from "../../../accounts.ts";
import { settings, speak, state, silentWav } from "./provider.ts";
import { voiceRoutes } from "./routes.ts";

test("speech reuses the selected FreeLLMAPI account and verifies audio against current settings", async (t) => {
  upsertPlugin("voice", false);
  upsertPlugin("freellmapi", false);
  let calls = 0;
  let response = () => new Response(silentWav(), { headers: { "content-type": "audio/wav", "x-provider": "google" } });
  let expectedBase = "https://speech.invalid/v1";
  let expectedKey = "synthetic-key";
  let expectedModel = "auto";
  let expectedVoice: string | undefined;
  t.mock.method(globalThis, "fetch", async (url: unknown, init: RequestInit) => {
    calls++;
    assert.equal(String(url), `${expectedBase}/audio/speech`);
    assert.equal(new Headers(init.headers).get("authorization"), `Bearer ${expectedKey}`);
    const input = JSON.parse(String(init.body));
    assert.equal(input.model, expectedModel);
    assert.equal(input.voice, expectedVoice);
    return response();
  });
  const account = accounts.create("freellmapi", "Speech test");
  accounts.writeCredentials(account, "test-speech", ["base-url", "key"], { "base-url": expectedBase, key: expectedKey });
  assert.equal(state().tts.ready, false, "An existing LLM connection must not turn speech on");
  await assert.rejects(speak("Test"), /Speech is off/);
  assert.equal(calls, 0);
  setConfig("voice", "tts", "freellmapi");
  assert.equal(settings().ttsModel, "auto");
  assert.equal(settings().ttsVoice, "");
  assert.equal(state().tts.ready, true);
  assert.equal(state().tts.check, null, "Configured is not verified");
  const clip = await speak("Neutral synthetic test sentence.");
  assert.equal(clip.format, "wav", "The gateway returned WAV even though MP3 was requested");
  assert.equal(clip.via, "FreeLLMAPI · google");
  assert.deepEqual(readFileSync(clip.path), silentWav());
  assert.equal(state().tts.check?.ok, true);
  const audio = await voiceRoutes.request(`/clip/${clip.id}.wav`);
  assert.equal(audio.headers.get("content-type"), "audio/wav");
  assert.equal((await audio.arrayBuffer()).byteLength, clip.bytes);
  assert.equal(accounts.list("voice").length, 0, "Do not duplicate the FreeLLMAPI key into another account");
  assert(!configValue("voice", "speechCheck")!.includes(expectedKey));
  setConfig("voice", "ttsModel", "chosen-tts-model"); expectedModel = "chosen-tts-model";
  assert.equal(state().tts.check, null, "A model change invalidates the earlier result");
  setConfig("voice", "ttsVoice", "speaker-one"); expectedVoice = "speaker-one";
  await speak("Explicit model and speaker.");
  assert.equal(state().tts.check?.ok, true);
  const second = accounts.create("freellmapi", "Another account");
  expectedBase = "https://other-speech.invalid/v1"; expectedKey = "another-synthetic-key";
  accounts.writeCredentials(second, "test-speech", ["base-url", "key"], { "base-url": expectedBase, key: expectedKey });
  setConfig("freellmapi", "account", String(second.id));
  assert.equal(state().tts.check, null, "Switching FreeLLMAPI accounts invalidates verification");
  await speak("Selected account.");
  assert.equal(state().tts.check?.ok, true);
  expectedKey = "rotated-synthetic-key";
  accounts.writeCredentials(second, "test-speech", ["key"], { key: expectedKey });
  assert.equal(state().tts.check, null, "Rotating the key invalidates verification");
  response = () => new Response("upstream echoed private input", { status: 401 });
  await assert.rejects(speak("Synthetic failure test"), /HTTP 401/);
  assert.equal(state().tts.check?.ok, false);
  assert(!state().tts.check?.error?.includes("private input"));
  for (const body of ["", '{"error":"not audio"}']) {
    response = () => new Response(body, { headers: { "content-type": "audio/mpeg" } });
    await assert.rejects(speak("Invalid audio test"), /empty or unsupported audio/);
    assert.equal(state().tts.check?.ok, false);
  }
  response = () => new Response(Buffer.concat([Buffer.from("ID3"), Buffer.alloc(30)]), { headers: { "content-type": "audio/mpeg" } });
  assert.equal((await speak("MP3 test")).format, "mp3");
  assert.equal(state().tts.check?.ok, true);
  accounts.remove(second); accounts.remove(account);
  assert.equal(state().tts.ready, false);
  assert.equal(state().tts.check, null);
  await assert.rejects(speak("Missing account"), /FreeLLMAPI is not configured/);
  setConfig("voice", "tts", "openai");
  assert.equal(state().tts.ready, false, "Mode alone is not sufficient without an endpoint");
  setConfig("voice", "ttsModel", ""); setConfig("voice", "ttsVoice", "");
  assert.equal(settings().ttsModel, "tts-1");
  assert.equal(settings().ttsVoice, "alloy");
  setConfig("voice", "tts", "piper");
  assert.equal(state().tts.ready, false, "Piper needs an installed binary and model");
});
